/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsIndexRouteImport } from './routes/alerts.index'
import { Route as AlertsAlertIdOverrideRouteImport } from './routes/alerts.$alertId.override'
import { Route as AlertsAlertIdDeferRouteImport } from './routes/alerts.$alertId.defer'
import { Route as AlertsAlertIdAcceptRouteImport } from './routes/alerts.$alertId.accept'

const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsAlertIdOverrideRoute = AlertsAlertIdOverrideRouteImport.update({
  id: '/alerts/$alertId/override',
  path: '/alerts/$alertId/override',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsAlertIdDeferRoute = AlertsAlertIdDeferRouteImport.update({
  id: '/alerts/$alertId/defer',
  path: '/alerts/$alertId/defer',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsAlertIdAcceptRoute = AlertsAlertIdAcceptRouteImport.update({
  id: '/alerts/$alertId/accept',
  path: '/alerts/$alertId/accept',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/patients': typeof PatientsRoute
  '/summary': typeof SummaryRoute
  '/alerts/': typeof AlertsIndexRoute
  '/alerts/$alertId/accept': typeof AlertsAlertIdAcceptRoute
  '/alerts/$alertId/defer': typeof AlertsAlertIdDeferRoute
  '/alerts/$alertId/override': typeof AlertsAlertIdOverrideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/patients': typeof PatientsRoute
  '/summary': typeof SummaryRoute
  '/alerts': typeof AlertsIndexRoute
  '/alerts/$alertId/accept': typeof AlertsAlertIdAcceptRoute
  '/alerts/$alertId/defer': typeof AlertsAlertIdDeferRoute
  '/alerts/$alertId/override': typeof AlertsAlertIdOverrideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/patients': typeof PatientsRoute
  '/summary': typeof SummaryRoute
  '/alerts/': typeof AlertsIndexRoute
  '/alerts/$alertId/accept': typeof AlertsAlertIdAcceptRoute
  '/alerts/$alertId/defer': typeof AlertsAlertIdDeferRoute
  '/alerts/$alertId/override': typeof AlertsAlertIdOverrideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/patients'
    | '/summary'
    | '/alerts/'
    | '/alerts/$alertId/accept'
    | '/alerts/$alertId/defer'
    | '/alerts/$alertId/override'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/patients'
    | '/summary'
    | '/alerts'
    | '/alerts/$alertId/accept'
    | '/alerts/$alertId/defer'
    | '/alerts/$alertId/override'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/patients'
    | '/summary'
    | '/alerts/'
    | '/alerts/$alertId/accept'
    | '/alerts/$alertId/defer'
    | '/alerts/$alertId/override'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  PatientsRoute: typeof PatientsRoute
  SummaryRoute: typeof SummaryRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  AlertsAlertIdAcceptRoute: typeof AlertsAlertIdAcceptRoute
  AlertsAlertIdDeferRoute: typeof AlertsAlertIdDeferRoute
  AlertsAlertIdOverrideRoute: typeof AlertsAlertIdOverrideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$alertId/override': {
      id: '/alerts/$alertId/override'
      path: '/alerts/$alertId/override'
      fullPath: '/alerts/$alertId/override'
      preLoaderRoute: typeof AlertsAlertIdOverrideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$alertId/defer': {
      id: '/alerts/$alertId/defer'
      path: '/alerts/$alertId/defer'
      fullPath: '/alerts/$alertId/defer'
      preLoaderRoute: typeof AlertsAlertIdDeferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$alertId/accept': {
      id: '/alerts/$alertId/accept'
      path: '/alerts/$alertId/accept'
      fullPath: '/alerts/$alertId/accept'
      preLoaderRoute: typeof AlertsAlertIdAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  PatientsRoute: PatientsRoute,
  SummaryRoute: SummaryRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  AlertsAlertIdAcceptRoute: AlertsAlertIdAcceptRoute,
  AlertsAlertIdDeferRoute: AlertsAlertIdDeferRoute,
  AlertsAlertIdOverrideRoute: AlertsAlertIdOverrideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
